[mypy]
python_version = 3.11
strict = True
warn_return_any = True
warn_unused_configs = True
warn_unused_ignores = False
disallow_untyped_defs = True
disallow_any_generics = True
ignore_missing_imports = True
disallow_untyped_decorators = False
plugins = pydantic.mypy

[mypy-tests.*]
disallow_untyped_defs = False
disable_error_code = attr-defined

[mypy-alembic.*]
ignore_errors = True
